name: .NET Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest  

    env:
      Solution_Name: ListDependencies.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build and Publish
      run: dotnet publish $env:Solution_Name /p:Configuration=Release --output published
